package: kubernetes
output: generated/kubernetes.gen.go
generate:
  models: true
  client: true
output-options:
  custom-doer:
    enabled: true
    import: common "github.com/SchwarzIT/community-stackit-go-client/internal/common"
    name: "common.Client"
  split-by-tags:
    verbose: false
    enabled: true
  extend-response:
  - field: HasError
    type: error
    description: "Aggregated error"
    apply-to: ["*"]
    imports: ["errors", "github.com/SchwarzIT/community-stackit-go-client/pkg/validate"]
    set: "validate.DefaultResponseErrorHandler(rsp)"
  copy:
  - from: include/cluster/wait.go
    to: cluster/wait.go
    trim: "cluster."
tidy:
  verbose: false
  functions:
  - replace: SkeService
    with: 
    prefix: true
  params:
  - replace: Id
    with: ID
    suffix: true
  schemas:
  - replace: v1
    with:
    prefix: true
  - replace: Id
    with: ID
    suffix: true
  - replace: Cri
    with: CRI
    match: true
  - replace: Cpu
    with: CPU
    match: true
