package: elasticsearch
output: generated/elasticsearch.gen.go
generate:
  models: true
  client: true
output-options:
  custom-doer:
    enabled: true
    import: common "github.com/SchwarzIT/community-stackit-go-client/internal/common"
    name: "common.Client"
  split-by-tags:
    verbose: false
    enabled: true
  extend-response:
  - field: HasError
    type: error
    description: "Aggregated error"
    apply-to: ["*"]
    imports: ["errors"]
  copy:
  - from: include/service.go
    to: service.go
    trim: "elasticsearch."
  - from: include/instances/wait.go
    to: instances/wait.go
    trim: "instances."
tidy:
  verbose: false
  functions:
  - replace: Id
    with: ID
    all: true
  - replace: Instance
    with: 
    prefix: true
  - replace: CredentialsGet
    with: List
    prefix: true
  - replace: Credentials
    with: 
    prefix: true
  - replace: CredentialGet
    with: Get
    prefix: true
  - replace: Offerings
    with:
    prefix: true
  params:
  - replace: Id
    with: ID
    all: true
  schemas:
  - replace: Id
    with: ID
    all: true
  - replace: Cf
    with: CF
    prefix: true
  - replace: Guid
    with: GUID
    all: true